name: Ingest Microsoft Entra Non-Interactive Sign-ins into Chronicle

on:
  workflow_dispatch:
  schedule:
    - cron: '*/15 * * * *'

jobs:
  ingest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r chronicle-scripts/entra-noninteractive-chronicle-ingestor/requirements.txt

      - name: Write Chronicle service account key to file
        shell: bash
        run: |
          echo "${{ secrets.CHRONICLE_CREDENTIALS_JSON }}" | base64 --decode > chronicle_sa.json

      - name: Run Entra non-interactive ingestion script
        env:
          PYTHONPATH: chronicle-scripts
          CHRONICLE_CUSTOMER_ID: ${{ secrets.CHRONICLE_CUSTOMER_ID }}
          CHRONICLE_REGION: ${{ secrets.CHRONICLE_REGION }}
          GOOGLE_APPLICATION_CREDENTIALS: chronicle_sa.json
          CHRONICLE_SERVICE_ACCOUNT: chronicle_sa.json
          CHRONICLE_NAMESPACE: ${{ secrets.CHRONICLE_NAMESPACE }}
          GRAPH_CLIENT_ID: ${{ secrets.GRAPH_CLIENT_ID }}
          GRAPH_CLIENT_SECRET: ${{ secrets.GRAPH_CLIENT_SECRET }}
          GRAPH_TENANT_ID: ${{ secrets.GRAPH_TENANT_ID }}
        run: |
          python chronicle-scripts/entra-noninteractive-chronicle-ingestor/main.py --creds-file chronicle_sa.json
