name: Ingest GitHub Audit Logs into Chronicle

on:
  workflow_dispatch:

jobs:
  ingest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r chronicle-scripts/github-chronicle-ingestor/requirements.txt

      - name: Write Chronicle service account key to file
        run: |
          echo "${{ secrets.CHRONICLE_CREDENTIALS_JSON }}" | base64 --decode > chronicle_sa.json

      - name: Run GitHub ingestion script
        env:
          PYTHONPATH: chronicle-scripts
          GOOGLE_APPLICATION_CREDENTIALS: chronicle_sa.json
          CHRONICLE_CUSTOMER_ID: ${{ secrets.CHRONICLE_CUSTOMER_ID }}
          CHRONICLE_REGION: ${{ secrets.CHRONICLE_REGION }}
          CHRONICLE_NAMESPACE: ${{ secrets.CHRONICLE_NAMESPACE }}
          CHRONICLE_SERVICE_ACCOUNT: chronicle_sa.json
          GITHUB_AUDIT_TOKEN: ${{ secrets.GITHUB_AUDIT_TOKEN }}
          GITHUB_AUDIT_URL: ${{ secrets.GITHUB_AUDIT_URL }}
        run: |
          python chronicle-scripts/github-chronicle-ingestor/main.py --creds-file chronicle_sa.json

