name: Ingest Snowflake Audit Logs into Chronicle

on:
  workflow_dispatch:

jobs:
  ingest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r chronicle-scripts/snowflake-chronicle-ingestor/requirements.txt

      - name: Write Chronicle service account key to file
        shell: bash
        run: |
          echo "${{ secrets.CHRONICLE_CREDENTIALS_JSON }}" | base64 --decode > chronicle_sa.json

      - name: Run Snowflake ingestion script
        env:
          PYTHONPATH: chronicle-scripts
          CHRONICLE_CUSTOMER_ID: ${{ secrets.CHRONICLE_CUSTOMER_ID }}
          CHRONICLE_REGION: ${{ secrets.CHRONICLE_REGION }}
          CHRONICLE_NAMESPACE: ${{ secrets.CHRONICLE_NAMESPACE }}
          GOOGLE_APPLICATION_CREDENTIALS: chronicle_sa.json
          CHRONICLE_SERVICE_ACCOUNT: chronicle_sa.json
          SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}
          SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}
          SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
          SNOWFLAKE_WAREHOUSE: ${{ secrets.SNOWFLAKE_WAREHOUSE }}
          SNOWFLAKE_ROLE: ${{ secrets.SNOWFLAKE_ROLE }}
        run: |
          python chronicle-scripts/snowflake-chronicle-ingestor/main.py --creds-file chronicle_sa.json

